#!/bin/sh
DJANGO_SESSION_EXPIRATION_TIMEOUT="1209600"
NOW=`date +%s`
TOUCH_FILE="/tmp/zabbix-"`basename $0`".touch"
if [ -f ${TOUCH_FILE} ]; then
        LAST_CHECK=`stat -c %Y ${TOUCH_FILE}`
else
        LAST_CHECK=${NOW}
fi
LAST_CHECK_DELTA=`expr 0${NOW} - 0${LAST_CHECK}`
MEMCACHED_HOST=`grep -A3 '\[memcached\]' /etc/zabbix/scripts/scripts.cfg | tr -d ' ' | grep host= | cut -f 2 -d =`
MEMCACHED_PORT=`grep -A3 '\[memcached\]' /etc/zabbix/scripts/scripts.cfg | tr -d ' ' | grep port= | cut -f 2 -d =`
if [ -z "${MEMCACHED_HOST}" ]; then
    MEMCACHED_HOST="localhost"
fi
if [ -z "${MEMCACHED_PORT}" ]; then
    MEMCACHED_PORT="11211"
fi
timeout 20s /usr/share/memcached/scripts/memcached-tool localhost:11211 dump 2>&1 | \
    cut -b -120 | \
    grep -a '^add.*django.contrib.sessions' | \
    awk 'BEGIN {lines=0} {if(($4-'$NOW'-'${DJANGO_SESSION_EXPIRATION_TIMEOUT}'+'${LAST_CHECK_DELTA}'>0) && ($5>60)){lines++}} END {print lines}'
touch ${TOUCH_FILE}

# /usr/share/memcached/scripts/memcached-tool out example:
# add default:1:django.contrib.sessions.cachez1czqocgf793f1td99m2fdpfvw31oer8 1 1536591902 60
# add default:1:django.contrib.sessions.cacheo7uz9bljri33ed0ygszwoet84t29x4r4 1 1536592024 60
# add default:1:django.contrib.sessions.cache0jk49tssan70g3c80ygtc5d9114zvo2h 1 1536591965 60
# add default:1:django.contrib.sessions.cachexgcjwu9u57lxfb0m9qr4cs0aa75kn12q 1 1536592211 210
#
# 1536592211 - session expiration date (by default +1MONTH from session start)
# this script count only session created period of last script run (timestamp delta of touch file)
# last column is SIZE of the record. 60 - empty session, generated by random HTTP requests.
# empty sessions is ignored by awk's ($5>60) condition. logged users has data inside session so
# memcached record will have greater size (last line on example)
