---
# oraclejdk
#
# Dependencies:
#
#   * common
#
# Example play:
#
#   roles:
#   - common
#   - oraclejdk

- name: Install debian needed pkgs
  apt:
    name: "{{ item }}"
  with_items: "{{ oraclejdk_debian_pkgs }}"

- name: Download Oracle Java
  shell: "curl -b gpw_e24=http%3A%2F%2Fwww.oracle.com -b oraclelicense=accept-securebackup-cookie -O -L {{ oraclejdk_url }}"
  args:
    executable: /bin/bash
    chdir: "{{ oraclejdk_tmp_dir }}"
    creates: "{{ oraclejdk_tmp_dir }}/{{ oraclejdk_file }}"
  when: not oraclejdk_file_from_raccoongang_s3

- name: Download Oracle Java from raccoongang S3 - "{{ s3_production_packages_bucket }}"
  get_url:
    url: "{{ oraclejdk_s3_url }}"
    dest: "{{ oraclejdk_tmp_dir }}/{{ oraclejdk_s3_file }}"
    force: yes
  when: oraclejdk_file_from_raccoongang_s3

- name: Create jvm dir
  file:
    path: /usr/lib/jvm
    state: directory
    owner: root
    group: root

- name: Untar Oracle Java
  shell: "tar -C /usr/lib/jvm -zxvf {{ oraclejdk_tmp_dir }}/{{ oraclejdk_file }}"
  args:
    executable: /bin/bash
    creates: "/usr/lib/jvm/{{ oraclejdk_base }}"

- name: Create symlink expected by elasticsearch
  file:
    src: "/usr/lib/jvm/{{ oraclejdk_base }}"
    dest: "{{ oraclejdk_link }}"
    state: link
    force: yes

- name: Update alternatives java
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/usr/lib/jvm/{{ oraclejdk_base }}/bin/{{ item }}"
  with_items:
    - java
    - javac
    - javaws
    - jarsigner

- name: Add JAVA_HOME for Oracle Java
  template:
    src: "java.sh.j2"
    dest: "/etc/profile.d/java.sh"
    owner: root
    group: root
    mode: "0755"
