---
- name: install azure with pip
  pip:
    name: azure
    version: "{{ azure_cli_version }}"

- name: install azure-storage with pip
  pip:
    name: azure-storage
    version: "{{ azure_storage_version }}"

