---
datadog_enabled: yes

datadog_api_key: ""

# default datadog.conf options
datadog_config: {}

# default checks enabled
datadog_checks: {}

# default user/group
datadog_user: dd-agent
datadog_group: root

# default apt repo
datadog_apt_repo: "deb https://apt.datadoghq.com/ stable 6"
datadog_apt_cache_valid_time: 3600

# default yum repo and keys
datadog_yum_repo: "https://yum.datadoghq.com/stable/6/{{ ansible_userspace_architecture }}/"
datadog_yum_gpgkey: "https://yum.datadoghq.com/DATADOG_RPM_KEY.public"
datadog_yum_gpgkey_new: "https://yum.datadoghq.com/DATADOG_RPM_KEY_E09422B3.public"

# Pin agent to a version. Highly recommended.
datadog_agent_version: "1:6.1.4-1"

# Set this to `yes` to allow agent downgrades on apt-based platforms.
# Internally, this uses `apt-get`'s `--force-yes` option. Use with caution.
datadog_agent_allow_downgrade: no
