insights_waffle_switches:
  enable_course_passing:
    active: 'off'
  enable_course_filters:
    active: 'off'
  display_verified_enrollment:
    active: 'off'
  enable_ccx_courses:
    active: 'off'
  display_course_name_in_nav:
    active: 'off'
  enable_learner_analytics:
    active: 'off'
  enable_learner_download:
    active: 'off'
  enable_problem_resp'on'se_download:
    active: 'off'
  show_navbar_demographics:
    active: 'off'
  enable_performance_learning_outcome:
    active: 'on'
  display_names_for_course_index:
    active: 'on'
  enable_video_preview:
    active: 'on'
  enable_engagement_videos_pages:
    active: 'on'
  enable_course_api:
    active: 'on'
  show_engagement_forum_activity:
    active: 'on'

