---
- name: add the mongodb signing key
  apt_key:
    id: "{{ MONGODB_APT_KEY }}"
    keyserver: "{{ MONGODB_APT_KEYSERVER }}"
    state: present
  tags:
    - install
    - install:system-requirements

- name: add the mongodb repo to the sources list
  apt_repository:
    repo: "{{ MONGODB_REPO }}"
    state: present
  tags:
    - install
    - install:system-requirements

- name: install mongo shell
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: yes
    force: yes
    update_cache: yes
  with_items: "{{ mongo_client_debian_pkgs }}"
  tags:
    - install
    - install:system-requirements
