---
- include_tasks: server_utils.yml
  when: not server_utils_role_finished

- name: Set flag to skip server_utils role on future calls
  set_fact:
    server_utils_role_finished: True
  when: not server_utils_role_finished
