---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role server_utils
# 
# Overview:
#
# Install useful interactive utilities for triange and debugging purposes.
# Typically these would not need to be available on servers as shell access
# is uneccessary.
# 
# Example play:
#
#

- name: Install ubuntu system packages
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present 
    update_cache: yes
  with_items: "{{ server_utils_debian_pkgs }}"
  when: ansible_distribution == 'Ubuntu'

- name: applying sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ sysctl_settings }}"
  ignore_errors: true
  become: true
  become_method: 'sudo'

- name: disabling email spam from cron about ubuntu upgrade
  file:
    path: "{{ item }}"
    state: absent
  become: true
  become_method: 'sudo'
  with_items:
    - "/etc/cron.daily/update-notifier-common"
    - "/etc/cron.weekly/update-notifier-common"
