backup_enabled: false

edx_backup_duplicity_profiles:
  - name: 'mysql'
    type: 'mysql'
    mysql_user: '{{ COMMON_MYSQL_READ_ONLY_USER }}'
    mysql_password: '{{ COMMON_MYSQL_READ_ONLY_PASS }}'
    mysql_host: '{{ EDXAPP_MYSQL_HOST | default("127.0.0.1") }}'

  - name: 'mongo'
    type: 'mongo'
    mongo_user: '{{ MONGO_ADMIN_USER | default("admin") }}'
    mongo_password: '{{ MONGO_ADMIN_PASSWORD }}'
    mongo_authdb: 'admin'
    mongo_host: '{{ EDXAPP_MONGO_HOSTS | default("127.0.0.1") }}'
