---

- name: Add zabbix-agent GPG key
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    " {{ zabbix_version[ansible_distribution]['repo_key'] }}"

- name: Add zabbix main repository
  yum_repository:
    name: zabbix
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version_latest }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    state: present
    description: Zabbix YUM repo

- name: Install zabbix-agent packages
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    "{{ zabbix_requirements[ansible_distribution] }}"
