# Installs memcached

- name: Install memcached
  apt:
    name: memcached
    state: present
    update_cache: yes
  tags:
    - install
    - install:memcache

- name: Set listen address to 0.0.0.0
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^-l \d+\.\d+\.\d+\.\d+'
    line: '-l 0.0.0.0'
  register: memcached_conf1

- name: Increase the memory limit
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^-m \d+'
    line: '-m 512'
  register: memcached_conf2

- name: Restart memcached
  service:
    name: memcached
    state: restarted
  when: memcached_conf1.changed or memcached_conf2.changed
