---
- name: edx-analytics-dashboard create_oauth2_client
  shell: >
      chdir={{ edxapp_code_dir }}
      {{ edxapp_venv_bin }}/python ./manage.py lms --settings=aws create_oauth2_client  \
      {{ INSIGHTS_BASE_URL }}/ \
      {{ INSIGHTS_BASE_URL }}/complete/edx-oidc/  \
      confidential \
      --username={{ SECRET_INSIGHTS_OAUTH2_APP_USERNAME }} \
      --client_name={{ SECRET_INSIGHTS_OAUTH2_APP_CLIENT_NAME }} \
      --client_id={{ SECRET_INSIGHTS_OAUTH2_KEY }} \
      --client_secret={{ SECRET_INSIGHTS_OAUTH2_SECRET }} \
      --trusted
  become_method: sudo
  become: yes
  become_user: "{{ edxapp_user }}"

