---
- name: Create insights waffle switches
  shell: >
    chdir={{ insights_code_dir }}
    export ANALYTICS_API_CFG={{ insights_environment['ANALYTICS_DASHBOARD_CFG'] }} && {{ insights_venv_dir }}/bin/python ./manage.py waffle_switch {{ item.key }} {{ item.value.active }} --create --settings={{ insights_environment['DJANGO_SETTINGS_MODULE'] }}
  with_dict: "{{ insights_waffle_switches }}"
  become_user: "{{ insights_user }}"
  environment: "{{ insights_environment }}"


