---

- name: Install unzip
  apt: pkg=unzip state=present

- name: create the nltk data directory and subdirectories
  file: path={{ NLTK_DATA_DIR }}/{{ item.path }} state=directory
  with_items: "{{ NLTK_DATA }}"
  tags:
    - deploy

- name: download nltk data
  get_url:
    dest: "{{ NLTK_DATA_DIR }}/{{ item.url|basename }}"
    url: "{{ item.url }}"
  with_items: "{{ NLTK_DATA }}"
  tags:
    - deploy

- name: unarchive nltk data
  unarchive:
    src: "{{ NLTK_DATA_DIR }}/{{ item.url|basename }}"
    dest: "{{ NLTK_DATA_DIR }}/{{ item.path }}"
    remote_src: yes
  with_items: "{{ NLTK_DATA }}"
  tags:
    - deploy
