---

- hosts: frontend
  gather_facts: yes
  become: yes
  vars:
    nginx: yes
    nginx_ssl: yes
    nginx_letsencrypt: no
    insights: no
    use_client_bundle_ssl: True
  roles:
    - { role: rg-nginx }
