---

- name: Configure instance(s)
  hosts: frontend
  become: True
  gather_facts: True
  roles:
    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''
    - role: nginx
      nginx_sites:
      - cms
      - lms
      nginx_default_sites:
      - lms
    - role: edxlocal
    - role: edxapp
    - role: demo
    - role: edx-user-attr
    - role: edx-powerbi
      when: powerbi
    - role: edx-laas
      when: laas
    - role: oauth_client_setup
    - role: custom
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
    - role: datadog
      when: COMMON_ENABLE_DATADOG
