---
- name: Bootstrap AWX instance(s)
  hosts: awx
  gather_facts: no
  become: True
  roles:
    - python

- name: Installing AWX
  hosts: awx
  become: True
  gather_facts: True
  roles:
    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''
    - role: awx
    - role: rg-nginx
      vars:
        nginx_ssl: no
    - role: rg-nginx
      vars:
        nginx_ssl: yes
