---

- name: Set ip address of services
  hosts: all
  become: False
  gather_facts: no
  tasks:
    - name: set instances ip addresses
      set_fact:
        mysql_host: "{{ hostvars['mysql'].ansible_host }}"
        memcached_host: "{{ hostvars['services'].ansible_host }}"
        mongo_hosts: "{{ hostvars['mongo'].ansible_host }}"
        elasticsearch_host: "{{ hostvars['services'].ansible_host }}"
        rabbit_master: "{{ hostvars['services'].ansible_host }}"
        xqueue_host: "{{ hostvars['services'].ansible_host }}"
        certs_host: "{{ hostvars['services'].ansible_host }}"
        forum_host: "{{ hostvars['services'].ansible_host }}"
      tags: [ "always" ]

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - role: python

- name: Setup mysql
  hosts: mysql
  become: True
  gather_facts: True
  roles:
    - role: common_vars
      when: False

    - role: edxapp
      when: False

    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''

    - role: mysql

- name: Setup mongo
  hosts: mongo
  become: True
  gather_facts: True
  roles:
    - role: common_vars
      when: False

    - role: edxapp
      when: False

    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''

    - role: mongo_3_2

- name: Setup services
  hosts: services
  become: True
  gather_facts: True
  roles:
    - role: common_vars
      when: False

    - role: edxapp
      when: False

    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''

    - role: nginx
      nginx_sites:
      - certs
      - forum
      - xqueue

    - role: edxlocal

    - role: memcache

    - role: rabbitmq

    - role: oraclejdk

    - role: elasticsearch

    - role: discovery
      when: SANDBOX_ENABLE_DISCOVERY is defined and SANDBOX_ENABLE_DISCOVERY

    - role: credentials
      when: SANDBOX_ENABLE_CREDENTIALS is defined and SANDBOX_ENABLE_CREDENTIALS

    - role: ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE | default(False)

    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
      when: SANDBOX_ENABLE_ECOMMERCE | default(False)

    - role: rg_instructor_analytics_log_collector
      when: EDXAPP_RG_INSTRUCTOR_ANALYTICS_ENABLE | default(False)

    - role: celerybeat
      when: EDXAPP_CELERY_BEAT.enabled | default(False)

    - role: analytics_api
      when: SANDBOX_ENABLE_ANALYTICS_API | default(False)

    - role: insights
      when: SANDBOX_ENABLE_INSIGHTS | default(False)

    - role: edx_notes_api
      when: EDXAPP_ENABLE_EDXNOTES | default(False)

    - role: forum

    - role: notifier

    - role: xqueue
      update_users: True

    - role: certs

- name: Configure LMS-CMS-Celery
  hosts: lms
  become: True
  gather_facts: True
  roles:
    - role: edx_notes_api
      when: False

    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''

    - role: nginx
      nginx_sites:
      - cms
      - lms
      nginx_default_sites:
      - lms

    - role: edxlocal

    - role: edxapp
      celery_worker: True

    - role: edxapp

    - role: demo

    - role: edx-user-attr

    - role: oauth_client_setup

- name: Post tasks for all instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - role: datadog
      when: COMMON_ENABLE_DATADOG

    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
