---

- name: Configure instance(s)
  hosts: app
  become: True
  gather_facts: True
  roles:
    - role: edxapp
      when: False
    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''
    - role: nginx
      rbenv_dir: "{{ forum_rbenv_dir }}"
      nginx_sites:
      - forum
    - role: edxlocal
    - role: memcache
    - role: rabbitmq
    - role: oraclejdk
    - role: elasticsearch
    - role: forum
    - role: notifier
    - role: edx_notes_api
      when: EDXAPP_ENABLE_EDXNOTES
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
    - role: datadog
      when: COMMON_ENABLE_DATADOG
