---

- name: Set ip address of services
  hosts: all
  become: False
  gather_facts: no
  tasks:
    - name: set instances ip addresses
      set_fact:
        mysql_host: "{{ hostvars['mysql'].ansible_host }}"
        memcached_host: "{{ hostvars['services'].ansible_host }}"
        mongo_hosts: "{{ hostvars['mongo'].ansible_host }}"
        elasticsearch_host: "{{ hostvars['services'].ansible_host }}"
        rabbit_master: "{{ hostvars['services'].ansible_host }}"
        xqueue_host: "{{ hostvars['services'].ansible_host }}"
        certs_host: "{{ hostvars['services'].ansible_host }}"
        forum_host: "{{ hostvars['services'].ansible_host }}"

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ''
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - role: edxlocal
      when: inventory_hostname == 'mysql'
      delegate_to: mysql

    - role: memcache
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: mongo_3_2
      when: inventory_hostname == 'mongo'
      delegate_to: mongo

    - role: rabbitmq
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: oraclejdk
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: elasticsearch
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: edxapp
      celery_worker: True
      when: inventory_hostname == 'lms'
      delegate_to: lms

    - role: edxapp
      when: inventory_hostname == 'lms'
      delegate_to: lms

    - role: ecommerce
      when:
        - SANDBOX_ENABLE_ECOMMERCE is defined
        - SANDBOX_ENABLE_ECOMMERCE
        - inventory_hostname == 'services'
      delegate_to: services

    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
      when:
        - SANDBOX_ENABLE_ECOMMERCE is defined
        - SANDBOX_ENABLE_ECOMMERCE
        - inventory_hostname == 'services'
      delegate_to: services

    - role: rg_instructor_analytics_log_collector
      when:
        - EDXAPP_RG_INSTRUCTOR_ANALYTICS_ENABLE | default(False)
        - inventory_hostname == 'services'
      delegate_to: services

    - role: celerybeat
      when: 
        - EDXAPP_CELERY_BEAT.enabled | default(False)
        - inventory_hostname == 'services'
      delegate_to: services

    - role: analytics_api
      when:
        - SANDBOX_ENABLE_ANALYTICS_API is defined
        - SANDBOX_ENABLE_ANALYTICS_API
        - inventory_hostname == 'services'
      delegate_to: services

    - role: insights
      when:
        - SANDBOX_ENABLE_INSIGHTS is defined
        - SANDBOX_ENABLE_INSIGHTS
        - inventory_hostname == 'services'
      delegate_to: services

    - role: edx_notes_api
      when: 
        - EDXAPP_ENABLE_EDXNOTES
        - inventory_hostname == 'services'
      delegate_to: services

    - role: demo
      when: inventory_hostname == 'lms'
      delegate_to: lms

    - role: oauth_client_setup
      when: inventory_hostname == 'lms'
      delegate_to: lms

    - role: forum
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: notifier
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: xqueue
      update_users: True
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: certs
      when: inventory_hostname == 'services'
      delegate_to: services

    - role: datadog
      when: COMMON_ENABLE_DATADOG

    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
