---

oraclejdk_version: "8u65"
# what the archive unpacks to
oraclejdk_base: "jdk1.8.0_65"
oraclejdk_build: "b17"
oraclejdk_platform: "linux"
oraclejdk_arch: "x64"
oraclejdk_file: "jdk-{{ oraclejdk_version }}-{{ oraclejdk_platform }}-{{ oraclejdk_arch }}.tar.gz"
oraclejdk_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oraclejdk_version }}-{{ oraclejdk_build }}/{{ oraclejdk_file }}"
oraclejdk_link: "/usr/lib/jvm/java-8-oracle"

oraclejdk_debian_pkgs:
  - curl

oraclejdk_file_from_raccoongang_s3: yes
s3_production_packages_bucket: edx-production-packages
s3_production_packages_folder: ficus-rg
oraclejdk_s3_file: jdk-8u65-linux-x64.tar.gz
oraclejdk_s3_url: "https://s3-eu-west-1.amazonaws.com/{{ s3_production_packages_bucket }}/{{ s3_production_packages_folder }}/{{ oraclejdk_s3_file }}"
oraclejdk_tmp_dir: /var/tmp

