---
- name: stop all processes
  shell: "{{ supervisor_ctl }} stop all"
  listen: "restart supervisor"

- name: restart edx supervisor 
  service:
    name: supervisor
    state: restarted
  listen: "restart supervisor"

- name: restart application
  supervisorctl:
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "{{ analytics_log_watcher_service_name }}"
  listen: "restart supervisor service"
